2018-03-06 23:24:22.897 -05:00 [DBG] Using Identity.Application as default scheme for authentication
2018-03-06 23:24:22.986 -05:00 [DBG] Using Identity.External as default scheme for sign-in
2018-03-06 23:24:22.991 -05:00 [DBG] Using Identity.External as default scheme for sign-out
2018-03-06 23:24:22.994 -05:00 [DBG] Using Identity.Application as default scheme for challenge
2018-03-06 23:24:22.997 -05:00 [DBG] Using Identity.Application as default scheme for forbid
2018-03-06 23:24:24.834 -05:00 [DBG] Starting token cleanup
2018-03-06 23:24:25.404 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-06 23:24:25.445 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-06 23:24:27.549 -05:00 [WRN] Heartbeat took longer than ""00:00:01"" at ""2018-03-07T04:24:27.5453948+00:00"".
2018-03-06 23:24:41.079 -05:00 [DBG] Request path /.well-known/openid-configuration matched to endpoint type Discovery
2018-03-06 23:24:41.104 -05:00 [DBG] Endpoint enabled: Discovery, successfully created handler: IdentityServer4.Endpoints.DiscoveryEndpoint
2018-03-06 23:24:41.106 -05:00 [INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
2018-03-06 23:24:41.113 -05:00 [DBG] Start discovery request
2018-03-06 23:24:47.840 -05:00 [ERR] An exception occurred in the database while iterating the results of a query for context type 'IdentityServer4.EntityFramework.DbContexts.ConfigurationDbContext'.
System.ArgumentException: Keyword not supported: 'initial catalog'.
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
System.ArgumentException: Keyword not supported: 'initial catalog'.
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
2018-03-06 23:24:48.385 -05:00 [INF] {
  "Name": "Unhandled Exception",
  "Category": "Error",
  "EventType": "Error",
  "Id": 3000,
  "Details": "System.ArgumentException: Keyword not supported: 'initial catalog'.\r\n   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)\r\n   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)\r\n   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)\r\n   at Microsoft.Data.Sqlite.SqliteConnection.set_ConnectionString(String value)\r\n   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)\r\n   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()\r\n   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)\r\n   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()\r\n   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()\r\n   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)\r\n   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)\r\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at IdentityServer4.EntityFramework.Stores.ResourceStore.GetAllResourcesAsync()\r\n   at IdentityServer4.Stores.IResourceStoreExtensions.<GetAllEnabledResourcesAsync>d__2.MoveNext() in C:\\local\\identity\\server4\\IdentityServer4\\src\\IdentityServer4\\Extensions\\IResourceStoreExtensions.cs:line 74\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer4.ResponseHandling.DiscoveryResponseGenerator.<CreateDiscoveryDocumentAsync>d__8.MoveNext() in C:\\local\\identity\\server4\\IdentityServer4\\src\\IdentityServer4\\ResponseHandling\\DiscoveryResponseGenerator.cs:line 164\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer4.Endpoints.DiscoveryEndpoint.<ProcessAsync>d__4.MoveNext() in C:\\local\\identity\\server4\\IdentityServer4\\src\\IdentityServer4\\Endpoints\\DiscoveryEndpoint.cs:line 58\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext() in C:\\local\\identity\\server4\\IdentityServer4\\src\\IdentityServer4\\Hosting\\IdentityServerMiddleware.cs:line 54",
  "Message": "Keyword not supported: 'initial catalog'.",
  "ActivityId": "0HLC3SD7FBMJR:00000002",
  "TimeStamp": "2018-03-07T04:24:48Z",
  "ProcessId": 12304,
  "LocalIpAddress": "127.0.0.1:1494",
  "RemoteIpAddress": "::1"
}
2018-03-06 23:24:48.407 -05:00 [FTL] Unhandled exception: System.ArgumentException: Keyword not supported: 'initial catalog'.
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at IdentityServer4.EntityFramework.Stores.ResourceStore.GetAllResourcesAsync()
   at IdentityServer4.Stores.IResourceStoreExtensions.<GetAllEnabledResourcesAsync>d__2.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Extensions\IResourceStoreExtensions.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.ResponseHandling.DiscoveryResponseGenerator.<CreateDiscoveryDocumentAsync>d__8.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\ResponseHandling\DiscoveryResponseGenerator.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Endpoints.DiscoveryEndpoint.<ProcessAsync>d__4.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Endpoints\DiscoveryEndpoint.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 54
2018-03-06 23:24:48.749 -05:00 [ERR] An exception occurred while calculating the database error page content. Skipping display of the database error page.
System.ArgumentException: Keyword not supported: 'initial catalog'.
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.CreateReadOnlyConnection()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.ExistsAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
2018-03-06 23:24:48.856 -05:00 [ERR] An unhandled exception has occurred while executing the request
System.ArgumentException: Keyword not supported: 'initial catalog'.
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at IdentityServer4.EntityFramework.Stores.ResourceStore.GetAllResourcesAsync()
   at IdentityServer4.Stores.IResourceStoreExtensions.<GetAllEnabledResourcesAsync>d__2.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Extensions\IResourceStoreExtensions.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.ResponseHandling.DiscoveryResponseGenerator.<CreateDiscoveryDocumentAsync>d__8.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\ResponseHandling\DiscoveryResponseGenerator.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Endpoints.DiscoveryEndpoint.<ProcessAsync>d__4.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Endpoints\DiscoveryEndpoint.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__3.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-03-06 23:24:59.991 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-06 23:24:59.996 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-06 23:24:59.999 -05:00 [DBG] Request path /.well-known/openid-configuration matched to endpoint type Discovery
2018-03-06 23:25:00.003 -05:00 [DBG] Endpoint enabled: Discovery, successfully created handler: IdentityServer4.Endpoints.DiscoveryEndpoint
2018-03-06 23:25:00.007 -05:00 [INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
2018-03-06 23:25:00.013 -05:00 [DBG] Start discovery request
2018-03-06 23:25:00.204 -05:00 [ERR] An exception occurred in the database while iterating the results of a query for context type 'IdentityServer4.EntityFramework.DbContexts.ConfigurationDbContext'.
System.ArgumentException: Keyword not supported: 'initial catalog'.
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
System.ArgumentException: Keyword not supported: 'initial catalog'.
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
2018-03-06 23:25:00.487 -05:00 [INF] {
  "Name": "Unhandled Exception",
  "Category": "Error",
  "EventType": "Error",
  "Id": 3000,
  "Details": "System.ArgumentException: Keyword not supported: 'initial catalog'.\r\n   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)\r\n   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)\r\n   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)\r\n   at Microsoft.Data.Sqlite.SqliteConnection.set_ConnectionString(String value)\r\n   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)\r\n   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()\r\n   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)\r\n   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()\r\n   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()\r\n   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)\r\n   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)\r\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at IdentityServer4.EntityFramework.Stores.ResourceStore.GetAllResourcesAsync()\r\n   at IdentityServer4.Stores.IResourceStoreExtensions.<GetAllEnabledResourcesAsync>d__2.MoveNext() in C:\\local\\identity\\server4\\IdentityServer4\\src\\IdentityServer4\\Extensions\\IResourceStoreExtensions.cs:line 74\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer4.ResponseHandling.DiscoveryResponseGenerator.<CreateDiscoveryDocumentAsync>d__8.MoveNext() in C:\\local\\identity\\server4\\IdentityServer4\\src\\IdentityServer4\\ResponseHandling\\DiscoveryResponseGenerator.cs:line 164\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer4.Endpoints.DiscoveryEndpoint.<ProcessAsync>d__4.MoveNext() in C:\\local\\identity\\server4\\IdentityServer4\\src\\IdentityServer4\\Endpoints\\DiscoveryEndpoint.cs:line 58\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext() in C:\\local\\identity\\server4\\IdentityServer4\\src\\IdentityServer4\\Hosting\\IdentityServerMiddleware.cs:line 54",
  "Message": "Keyword not supported: 'initial catalog'.",
  "ActivityId": "0HLC3SD7FBMJR:00000003",
  "TimeStamp": "2018-03-07T04:25:00Z",
  "ProcessId": 12304,
  "LocalIpAddress": "127.0.0.1:1494",
  "RemoteIpAddress": "::1"
}
2018-03-06 23:25:00.509 -05:00 [FTL] Unhandled exception: System.ArgumentException: Keyword not supported: 'initial catalog'.
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at IdentityServer4.EntityFramework.Stores.ResourceStore.GetAllResourcesAsync()
   at IdentityServer4.Stores.IResourceStoreExtensions.<GetAllEnabledResourcesAsync>d__2.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Extensions\IResourceStoreExtensions.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.ResponseHandling.DiscoveryResponseGenerator.<CreateDiscoveryDocumentAsync>d__8.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\ResponseHandling\DiscoveryResponseGenerator.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Endpoints.DiscoveryEndpoint.<ProcessAsync>d__4.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Endpoints\DiscoveryEndpoint.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 54
2018-03-06 23:25:00.937 -05:00 [ERR] An exception occurred while calculating the database error page content. Skipping display of the database error page.
System.ArgumentException: Keyword not supported: 'initial catalog'.
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.CreateReadOnlyConnection()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.ExistsAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
2018-03-06 23:25:01.060 -05:00 [ERR] An unhandled exception has occurred while executing the request
System.ArgumentException: Keyword not supported: 'initial catalog'.
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at IdentityServer4.EntityFramework.Stores.ResourceStore.GetAllResourcesAsync()
   at IdentityServer4.Stores.IResourceStoreExtensions.<GetAllEnabledResourcesAsync>d__2.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Extensions\IResourceStoreExtensions.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.ResponseHandling.DiscoveryResponseGenerator.<CreateDiscoveryDocumentAsync>d__8.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\ResponseHandling\DiscoveryResponseGenerator.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Endpoints.DiscoveryEndpoint.<ProcessAsync>d__4.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Endpoints\DiscoveryEndpoint.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__3.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-03-06 23:26:57.023 -05:00 [DBG] Using Identity.Application as default scheme for authentication
2018-03-06 23:26:57.088 -05:00 [DBG] Using Identity.External as default scheme for sign-in
2018-03-06 23:26:57.092 -05:00 [DBG] Using Identity.External as default scheme for sign-out
2018-03-06 23:26:57.095 -05:00 [DBG] Using Identity.Application as default scheme for challenge
2018-03-06 23:26:57.097 -05:00 [DBG] Using Identity.Application as default scheme for forbid
2018-03-06 23:26:57.474 -05:00 [DBG] Starting token cleanup
2018-03-06 23:26:57.959 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-06 23:26:57.990 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-06 23:27:09.871 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-06 23:27:09.874 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-06 23:27:09.884 -05:00 [DBG] Request path /.well-known/openid-configuration matched to endpoint type Discovery
2018-03-06 23:27:09.913 -05:00 [DBG] Endpoint enabled: Discovery, successfully created handler: IdentityServer4.Endpoints.DiscoveryEndpoint
2018-03-06 23:27:09.916 -05:00 [INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
2018-03-06 23:27:09.925 -05:00 [DBG] Start discovery request
2018-03-06 23:27:15.244 -05:00 [DBG] Found ["openid","profile","api1"] as all scopes in database
2018-03-06 23:27:25.955 -05:00 [DBG] Request path /.well-known/openid-configuration matched to endpoint type Discovery
2018-03-06 23:27:25.959 -05:00 [DBG] Endpoint enabled: Discovery, successfully created handler: IdentityServer4.Endpoints.DiscoveryEndpoint
2018-03-06 23:27:25.962 -05:00 [INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
2018-03-06 23:27:25.965 -05:00 [DBG] Start discovery request
2018-03-06 23:27:26.887 -05:00 [DBG] Found ["openid","profile","api1"] as all scopes in database
2018-03-06 23:27:27.286 -05:00 [DBG] Request path /.well-known/openid-configuration/jwks matched to endpoint type Discovery
2018-03-06 23:27:27.290 -05:00 [DBG] Endpoint enabled: Discovery, successfully created handler: IdentityServer4.Endpoints.DiscoveryKeyEndpoint
2018-03-06 23:27:27.294 -05:00 [INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryKeyEndpoint for /.well-known/openid-configuration/jwks
2018-03-06 23:27:27.301 -05:00 [DBG] Start key discovery request
2018-03-06 23:27:27.501 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-06 23:27:27.504 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-06 23:27:27.506 -05:00 [DBG] Request path /connect/authorize matched to endpoint type Authorize
2018-03-06 23:27:27.514 -05:00 [DBG] Endpoint enabled: Authorize, successfully created handler: IdentityServer4.Endpoints.AuthorizeEndpoint
2018-03-06 23:27:27.517 -05:00 [INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeEndpoint for /connect/authorize
2018-03-06 23:27:27.524 -05:00 [DBG] Start authorize request
2018-03-06 23:27:27.534 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-06 23:27:27.545 -05:00 [DBG] No user present in authorize request
2018-03-06 23:27:27.558 -05:00 [DBG] Start authorize request protocol validation
2018-03-06 23:27:29.752 -05:00 [DBG] mvc found in database: true
2018-03-06 23:27:29.764 -05:00 [DBG] Checking for PKCE parameters
2018-03-06 23:27:29.768 -05:00 [DBG] No PKCE used.
2018-03-06 23:27:29.796 -05:00 [ERR] Invalid grant type for client: hybrid
{
  "ClientId": "mvc",
  "ClientName": "MVC Client",
  "RedirectUri": "http://localhost:5002/signin-oidc",
  "AllowedRedirectUris": [
    "http://localhost:5002/signin-oidc",
    "http://localhost:4201/auth-callback/"
  ],
  "SubjectId": "anonymous",
  "ResponseType": "code id_token",
  "ResponseMode": "form_post",
  "GrantType": "hybrid",
  "RequestedScopes": "",
  "State": "CfDJ8IJKgI8JBRlAuAlBQRfQhz4koCd4gSntwnHsETv3c1EULGCnu8iEaJh1wVSUMFy0whXT0SHICDvfAAZlz1OvQTNf6Vf9AI007PIJ_81qUA8a2zzTXcjOMzqop_u-VDh--6pKxapfPo6os5-1KV1cke1jrbOFVJeeIC1nPPrm4obPXI3zcgiaLKPhwxI5y24FyeQI4hV4tB43fJ4pj63VLuVMhR11JRsUtp8AWVgQ1FtpwaqMx9idgkIKZX9KtYXS4f2VRIKHfuMDQjOmfCeWrFR__RMygX5SUFgm279epeLepiLd3Kg3lB_iiWE-rBmeW9ek7iL-LTGx3eqIc9Benbc",
  "Raw": {
    "client_id": "mvc",
    "redirect_uri": "http://localhost:5002/signin-oidc",
    "response_type": "code id_token",
    "scope": "openid profile api1 offline_access",
    "response_mode": "form_post",
    "nonce": "636559936474138029.ZTczMmM5N2YtYTczMy00MzkzLTlhNTAtODg3MTAyMjljNDAzYzEyNjdmYWMtNGEzMC00OGRhLTgyNGQtMGI1Y2Y5MzAxOWIw",
    "state": "CfDJ8IJKgI8JBRlAuAlBQRfQhz4koCd4gSntwnHsETv3c1EULGCnu8iEaJh1wVSUMFy0whXT0SHICDvfAAZlz1OvQTNf6Vf9AI007PIJ_81qUA8a2zzTXcjOMzqop_u-VDh--6pKxapfPo6os5-1KV1cke1jrbOFVJeeIC1nPPrm4obPXI3zcgiaLKPhwxI5y24FyeQI4hV4tB43fJ4pj63VLuVMhR11JRsUtp8AWVgQ1FtpwaqMx9idgkIKZX9KtYXS4f2VRIKHfuMDQjOmfCeWrFR__RMygX5SUFgm279epeLepiLd3Kg3lB_iiWE-rBmeW9ek7iL-LTGx3eqIc9Benbc",
    "x-client-SKU": "ID_NET",
    "x-client-ver": "2.1.4.0"
  }
}
2018-03-06 23:27:29.812 -05:00 [ERR] Request validation failed
2018-03-06 23:27:29.815 -05:00 [INF] {
  "ClientId": "mvc",
  "ClientName": "MVC Client",
  "RedirectUri": "http://localhost:5002/signin-oidc",
  "AllowedRedirectUris": [
    "http://localhost:5002/signin-oidc",
    "http://localhost:4201/auth-callback/"
  ],
  "SubjectId": "anonymous",
  "ResponseType": "code id_token",
  "ResponseMode": "form_post",
  "GrantType": "hybrid",
  "RequestedScopes": "",
  "State": "CfDJ8IJKgI8JBRlAuAlBQRfQhz4koCd4gSntwnHsETv3c1EULGCnu8iEaJh1wVSUMFy0whXT0SHICDvfAAZlz1OvQTNf6Vf9AI007PIJ_81qUA8a2zzTXcjOMzqop_u-VDh--6pKxapfPo6os5-1KV1cke1jrbOFVJeeIC1nPPrm4obPXI3zcgiaLKPhwxI5y24FyeQI4hV4tB43fJ4pj63VLuVMhR11JRsUtp8AWVgQ1FtpwaqMx9idgkIKZX9KtYXS4f2VRIKHfuMDQjOmfCeWrFR__RMygX5SUFgm279epeLepiLd3Kg3lB_iiWE-rBmeW9ek7iL-LTGx3eqIc9Benbc",
  "Raw": {
    "client_id": "mvc",
    "redirect_uri": "http://localhost:5002/signin-oidc",
    "response_type": "code id_token",
    "scope": "openid profile api1 offline_access",
    "response_mode": "form_post",
    "nonce": "636559936474138029.ZTczMmM5N2YtYTczMy00MzkzLTlhNTAtODg3MTAyMjljNDAzYzEyNjdmYWMtNGEzMC00OGRhLTgyNGQtMGI1Y2Y5MzAxOWIw",
    "state": "CfDJ8IJKgI8JBRlAuAlBQRfQhz4koCd4gSntwnHsETv3c1EULGCnu8iEaJh1wVSUMFy0whXT0SHICDvfAAZlz1OvQTNf6Vf9AI007PIJ_81qUA8a2zzTXcjOMzqop_u-VDh--6pKxapfPo6os5-1KV1cke1jrbOFVJeeIC1nPPrm4obPXI3zcgiaLKPhwxI5y24FyeQI4hV4tB43fJ4pj63VLuVMhR11JRsUtp8AWVgQ1FtpwaqMx9idgkIKZX9KtYXS4f2VRIKHfuMDQjOmfCeWrFR__RMygX5SUFgm279epeLepiLd3Kg3lB_iiWE-rBmeW9ek7iL-LTGx3eqIc9Benbc",
    "x-client-SKU": "ID_NET",
    "x-client-ver": "2.1.4.0"
  }
}
2018-03-06 23:27:29.892 -05:00 [INF] {
  "Name": "Token Issued Failure",
  "Category": "Token",
  "EventType": "Failure",
  "Id": 2001,
  "ClientId": "mvc",
  "ClientName": "MVC Client",
  "RedirectUri": "http://localhost:5002/signin-oidc",
  "Endpoint": "Authorize",
  "Scopes": "",
  "GrantType": "hybrid",
  "Error": "unauthorized_client",
  "ActivityId": "0HLC3SEKV68UQ:00000005",
  "TimeStamp": "2018-03-07T04:27:29Z",
  "ProcessId": 22284,
  "LocalIpAddress": "127.0.0.1:5671",
  "RemoteIpAddress": "::1"
}
2018-03-06 23:27:30.127 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-06 23:27:30.131 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 04:20:40.392 -05:00 [FTL] Application startup exception
System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
   at System.Text.Encoding.GetBytes(String s)
   at IdentityServerWithAspIdAndEF.Startup.ConfigureServices(IServiceCollection services) in E:\Combined_AspNetIdentity_and_EntityFrameworkStorage\src\IdentityServerWithAspIdAndEF\Startup.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
2018-03-07 04:20:40.898 -05:00 [DBG] Starting token cleanup
2018-03-07 04:22:36.510 -05:00 [DBG] Using Identity.Application as default scheme for authentication
2018-03-07 04:22:36.593 -05:00 [DBG] Using Identity.External as default scheme for sign-in
2018-03-07 04:22:36.597 -05:00 [DBG] Using Identity.External as default scheme for sign-out
2018-03-07 04:22:36.599 -05:00 [DBG] Using Identity.Application as default scheme for challenge
2018-03-07 04:22:36.602 -05:00 [DBG] Using Identity.Application as default scheme for forbid
2018-03-07 04:22:38.668 -05:00 [DBG] Starting token cleanup
2018-03-07 04:22:41.773 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 04:22:42.243 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 04:24:24.044 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 04:24:24.065 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 04:30:53.187 -05:00 [DBG] Using Identity.Application as default scheme for authentication
2018-03-07 04:30:53.284 -05:00 [DBG] Using Identity.External as default scheme for sign-in
2018-03-07 04:30:53.287 -05:00 [DBG] Using Identity.External as default scheme for sign-out
2018-03-07 04:30:53.289 -05:00 [DBG] Using Identity.Application as default scheme for challenge
2018-03-07 04:30:53.292 -05:00 [DBG] Using Identity.Application as default scheme for forbid
2018-03-07 04:30:54.069 -05:00 [DBG] Starting token cleanup
2018-03-07 04:30:55.880 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 04:30:55.929 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 04:31:15.115 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 04:31:15.121 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 12:14:34.994 -05:00 [DBG] Using Identity.Application as default scheme for authentication
2018-03-07 12:14:35.078 -05:00 [DBG] Using Identity.External as default scheme for sign-in
2018-03-07 12:14:35.081 -05:00 [DBG] Using Identity.External as default scheme for sign-out
2018-03-07 12:14:35.083 -05:00 [DBG] Using Identity.Application as default scheme for challenge
2018-03-07 12:14:35.084 -05:00 [DBG] Using Identity.Application as default scheme for forbid
2018-03-07 12:14:36.515 -05:00 [DBG] Starting token cleanup
2018-03-07 12:14:38.880 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 12:14:38.923 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 12:15:09.415 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 12:15:09.418 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 12:15:09.506 -05:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-03-07 12:15:09.580 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 12:15:09.584 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:12:53.840 -05:00 [DBG] Using Identity.Application as default scheme for authentication
2018-03-07 21:12:54.106 -05:00 [DBG] Using Identity.External as default scheme for sign-in
2018-03-07 21:12:54.109 -05:00 [DBG] Using Identity.External as default scheme for sign-out
2018-03-07 21:12:54.112 -05:00 [DBG] Using Identity.Application as default scheme for challenge
2018-03-07 21:12:54.115 -05:00 [DBG] Using Identity.Application as default scheme for forbid
2018-03-07 21:12:55.810 -05:00 [DBG] Starting token cleanup
2018-03-07 21:12:59.940 -05:00 [WRN] Heartbeat took longer than ""00:00:01"" at ""2018-03-08T02:12:59.8652660+00:00"".
2018-03-07 21:13:01.807 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:13:01.880 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:13:25.010 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:13:25.016 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:13:26.133 -05:00 [ERR] An unhandled exception has occurred while executing the request
System.InvalidOperationException: Unable to resolve service for type 'IdentityServerWithAspIdAndEF.Services.IEmailSender' while attempting to activate 'IdentityServer4.Authorize.UI.AccountController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__3.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-03-07 21:15:05.520 -05:00 [DBG] Using Identity.Application as default scheme for authentication
2018-03-07 21:15:05.580 -05:00 [DBG] Using Identity.External as default scheme for sign-in
2018-03-07 21:15:05.583 -05:00 [DBG] Using Identity.External as default scheme for sign-out
2018-03-07 21:15:05.586 -05:00 [DBG] Using Identity.Application as default scheme for challenge
2018-03-07 21:15:05.591 -05:00 [DBG] Using Identity.Application as default scheme for forbid
2018-03-07 21:15:05.948 -05:00 [DBG] Starting token cleanup
2018-03-07 21:15:06.504 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:15:06.536 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:15:23.076 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:15:23.079 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:15:28.088 -05:00 [ERR] An unhandled exception has occurred while executing the request
System.InvalidOperationException: The partial view '_ValidationScriptsPartial' was not found. The following locations were searched:
/Views/Account/_ValidationScriptsPartial.cshtml
/Views/Shared/_ValidationScriptsPartial.cshtml
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.<RenderPartialCoreAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.<PartialAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AspNetCore._Views_Account_Register_cshtml.<<ExecuteAsync>b__15_11>d.MoveNext() in E:\Combined_AspNetIdentity_and_EntityFrameworkStorage\src\IdentityServerWithAspIdAndEF\Views\Account\Register.cshtml:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.<RenderSectionAsyncCore>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.RenderSection(String name, Boolean required)
   at AspNetCore._Views_Shared__Layout_cshtml.<>c__DisplayClass24_0.<<ExecuteAsync>b__5>d.MoveNext() in E:\Combined_AspNetIdentity_and_EntityFrameworkStorage\src\IdentityServerWithAspIdAndEF\Views\Shared\_Layout.cshtml:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.<SetOutputContentAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNetCore._Views_Shared__Layout_cshtml.<ExecuteAsync>d__24.MoveNext() in E:\Combined_AspNetIdentity_and_EntityFrameworkStorage\src\IdentityServerWithAspIdAndEF\Views\Shared\_Layout.cshtml:line 7
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderLayoutAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__3.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-03-07 21:17:53.304 -05:00 [DBG] Using Identity.Application as default scheme for authentication
2018-03-07 21:17:53.459 -05:00 [DBG] Using Identity.External as default scheme for sign-in
2018-03-07 21:17:53.467 -05:00 [DBG] Using Identity.External as default scheme for sign-out
2018-03-07 21:17:53.471 -05:00 [DBG] Using Identity.Application as default scheme for challenge
2018-03-07 21:17:53.480 -05:00 [DBG] Using Identity.Application as default scheme for forbid
2018-03-07 21:17:54.119 -05:00 [DBG] Starting token cleanup
2018-03-07 21:17:55.468 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:17:55.559 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:18:28.187 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:18:28.199 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:19:33.120 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:19:33.123 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:19:37.854 -05:00 [ERR] Failed executing DbCommand (893ms) [Parameters=[@__normalizedUserName_0='?' (Size = 256)], CommandType='"Text"', CommandTimeout='30']
SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[Address], [u].[ConcurrencyStamp], [u].[Document], [u].[Email], [u].[EmailConfirmed], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[Names], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[Phone], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Address'.
Invalid column name 'Document'.
Invalid column name 'Names'.
Invalid column name 'Phone'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__108_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
ClientConnectionId:eb0ac7f9-4430-44f0-a3d2-1976efbe0f65
Error Number:207,State:1,Class:16
2018-03-07 21:19:38.823 -05:00 [ERR] An exception occurred in the database while iterating the results of a query for context type 'IdentityServerWithAspIdAndEF.Data.ApplicationDbContext'.
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Address'.
Invalid column name 'Document'.
Invalid column name 'Names'.
Invalid column name 'Phone'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__108_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.<FirstOrDefault_>d__165`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
ClientConnectionId:eb0ac7f9-4430-44f0-a3d2-1976efbe0f65
Error Number:207,State:1,Class:16
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Address'.
Invalid column name 'Document'.
Invalid column name 'Names'.
Invalid column name 'Phone'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__108_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.<FirstOrDefault_>d__165`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
ClientConnectionId:eb0ac7f9-4430-44f0-a3d2-1976efbe0f65
Error Number:207,State:1,Class:16
2018-03-07 21:19:39.208 -05:00 [ERR] An exception occurred in the database while iterating the results of a query for context type 'IdentityServerWithAspIdAndEF.Data.ApplicationDbContext'.
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Address'.
Invalid column name 'Document'.
Invalid column name 'Names'.
Invalid column name 'Phone'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__108_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.<FirstOrDefault_>d__165`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__23`1.MoveNext()
ClientConnectionId:eb0ac7f9-4430-44f0-a3d2-1976efbe0f65
Error Number:207,State:1,Class:16
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Address'.
Invalid column name 'Document'.
Invalid column name 'Names'.
Invalid column name 'Phone'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__108_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.<FirstOrDefault_>d__165`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__23`1.MoveNext()
ClientConnectionId:eb0ac7f9-4430-44f0-a3d2-1976efbe0f65
Error Number:207,State:1,Class:16
2018-03-07 21:19:58.017 -05:00 [ERR] Failed executing DbCommand (410ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
CREATE TABLE [AspNetRoles] (
    [Id] nvarchar(450) NOT NULL,
    [ConcurrencyStamp] nvarchar(max) NULL,
    [Name] nvarchar(256) NULL,
    [NormalizedName] nvarchar(256) NULL,
    CONSTRAINT [PK_AspNetRoles] PRIMARY KEY ([Id])
);
System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'AspNetRoles' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:eb0ac7f9-4430-44f0-a3d2-1976efbe0f65
Error Number:2714,State:6,Class:16
2018-03-07 21:19:58.080 -05:00 [ERR] An error occurred while applying the migrations for 'IdentityServerWithAspIdAndEF.Data.ApplicationDbContext'. See InnerException for details.System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'AspNetRoles' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
ClientConnectionId:eb0ac7f9-4430-44f0-a3d2-1976efbe0f65
Error Number:2714,State:6,Class:16
2018-03-07 21:19:58.244 -05:00 [ERR] An unhandled exception has occurred while executing the request
System.InvalidOperationException: An error occurred while applying the migrations for 'IdentityServerWithAspIdAndEF.Data.ApplicationDbContext'. See InnerException for details.System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'AspNetRoles' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
ClientConnectionId:eb0ac7f9-4430-44f0-a3d2-1976efbe0f65
Error Number:2714,State:6,Class:16 ---> System.Data.SqlClient.SqlException: There is already an object named 'AspNetRoles' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-03-07 21:20:52.663 -05:00 [DBG] Using Identity.Application as default scheme for authentication
2018-03-07 21:20:52.781 -05:00 [DBG] Using Identity.External as default scheme for sign-in
2018-03-07 21:20:52.785 -05:00 [DBG] Using Identity.External as default scheme for sign-out
2018-03-07 21:20:52.791 -05:00 [DBG] Using Identity.Application as default scheme for challenge
2018-03-07 21:20:52.795 -05:00 [DBG] Using Identity.Application as default scheme for forbid
2018-03-07 21:20:53.184 -05:00 [DBG] Starting token cleanup
2018-03-07 21:20:54.556 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:20:54.588 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:21:09.827 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:21:09.834 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:22:00.985 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:22:00.990 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:22:11.721 -05:00 [WRN] User e7206bae-632a-4a41-bab7-1c8975bc9510 validation failed: DuplicateUserName.
2018-03-07 21:22:46.987 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:22:46.991 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:22:55.248 -05:00 [INF] User created a new account with password.
2018-03-07 21:22:55.752 -05:00 [DBG] Augmenting SignInContext
2018-03-07 21:22:57.419 -05:00 [DBG] Adding idp claim with value: local
2018-03-07 21:22:57.424 -05:00 [DBG] Adding amr claim with value: pwd
2018-03-07 21:22:57.428 -05:00 [DBG] Adding auth_time claim with value: 1520475775
2018-03-07 21:22:57.438 -05:00 [INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
2018-03-07 21:22:57.673 -05:00 [INF] AuthenticationScheme: Identity.Application signed in.
2018-03-07 21:22:57.677 -05:00 [INF] User created a new account with password.
2018-03-07 21:22:57.714 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-07 21:22:57.719 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-07 21:43:49.660 -05:00 [DBG] Using Identity.Application as default scheme for authentication
2018-03-07 21:43:49.747 -05:00 [DBG] Using Identity.External as default scheme for sign-in
2018-03-07 21:43:49.751 -05:00 [DBG] Using Identity.External as default scheme for sign-out
2018-03-07 21:43:49.753 -05:00 [DBG] Using Identity.Application as default scheme for challenge
2018-03-07 21:43:49.758 -05:00 [DBG] Using Identity.Application as default scheme for forbid
2018-03-07 21:43:50.193 -05:00 [DBG] Starting token cleanup
2018-03-07 21:43:50.834 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-07 21:43:50.876 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-07 21:44:09.190 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-07 21:44:09.196 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-07 21:44:14.255 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-07 21:44:14.258 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-07 21:44:14.456 -05:00 [INF] AuthenticationScheme: Identity.Application signed out.
2018-03-07 21:44:14.476 -05:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-03-07 21:44:14.479 -05:00 [INF] AuthenticationScheme: Identity.TwoFactorUserId signed out.
2018-03-07 21:44:14.815 -05:00 [INF] {
  "Name": "User Logout Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1002,
  "SubjectId": "23b76c69-082a-4430-bb6a-ed16cd61dcf8",
  "DisplayName": "correo@correo.com",
  "ActivityId": "0HLC4JPM7QNTH:00000003",
  "TimeStamp": "2018-03-08T02:44:14Z",
  "ProcessId": 19224,
  "LocalIpAddress": "127.0.0.1:3500",
  "RemoteIpAddress": "::1"
}
2018-03-07 21:45:19.981 -05:00 [DBG] Using Identity.Application as default scheme for authentication
2018-03-07 21:45:20.058 -05:00 [DBG] Using Identity.External as default scheme for sign-in
2018-03-07 21:45:20.063 -05:00 [DBG] Using Identity.External as default scheme for sign-out
2018-03-07 21:45:20.065 -05:00 [DBG] Using Identity.Application as default scheme for challenge
2018-03-07 21:45:20.068 -05:00 [DBG] Using Identity.Application as default scheme for forbid
2018-03-07 21:45:20.423 -05:00 [DBG] Starting token cleanup
2018-03-07 21:45:23.108 -05:00 [WRN] Heartbeat took longer than ""00:00:01"" at ""2018-03-08T02:45:23.0925951+00:00"".
2018-03-07 21:47:14.268 -05:00 [ERR] Failed executing DbCommand (488ms) [Parameters=[@__normalizedUserName_0='?' (Size = 256)], CommandType='"Text"', CommandTimeout='30']
SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[ConcurrencyStamp], [u].[Email], [u].[EmailConfirmed], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[Phone], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Phone'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__108_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
ClientConnectionId:a6d8cd5d-0593-46b3-bfa3-5bce8df30652
Error Number:207,State:1,Class:16
2018-03-07 21:47:15.136 -05:00 [ERR] An exception occurred in the database while iterating the results of a query for context type 'IdentityServerWithAspIdAndEF.Data.ApplicationDbContext'.
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Phone'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__108_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.<FirstOrDefault_>d__165`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
ClientConnectionId:a6d8cd5d-0593-46b3-bfa3-5bce8df30652
Error Number:207,State:1,Class:16
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Phone'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__108_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.<FirstOrDefault_>d__165`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
ClientConnectionId:a6d8cd5d-0593-46b3-bfa3-5bce8df30652
Error Number:207,State:1,Class:16
2018-03-07 21:47:15.476 -05:00 [ERR] An exception occurred in the database while iterating the results of a query for context type 'IdentityServerWithAspIdAndEF.Data.ApplicationDbContext'.
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Phone'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__108_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.<FirstOrDefault_>d__165`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__23`1.MoveNext()
ClientConnectionId:a6d8cd5d-0593-46b3-bfa3-5bce8df30652
Error Number:207,State:1,Class:16
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Phone'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__108_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.<FirstOrDefault_>d__165`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__23`1.MoveNext()
ClientConnectionId:a6d8cd5d-0593-46b3-bfa3-5bce8df30652
Error Number:207,State:1,Class:16
2018-03-07 22:26:41.660 -05:00 [DBG] Using Identity.Application as default scheme for authentication
2018-03-07 22:26:41.813 -05:00 [DBG] Using Identity.External as default scheme for sign-in
2018-03-07 22:26:41.815 -05:00 [DBG] Using Identity.External as default scheme for sign-out
2018-03-07 22:26:41.817 -05:00 [DBG] Using Identity.Application as default scheme for challenge
2018-03-07 22:26:41.820 -05:00 [DBG] Using Identity.Application as default scheme for forbid
2018-03-07 22:26:43.677 -05:00 [DBG] Starting token cleanup
2018-03-07 22:28:47.104 -05:00 [INF] User created a new account with password.
2018-03-07 22:28:47.842 -05:00 [DBG] Augmenting SignInContext
2018-03-07 22:28:49.649 -05:00 [DBG] Adding idp claim with value: local
2018-03-07 22:28:49.652 -05:00 [DBG] Adding amr claim with value: pwd
2018-03-07 22:28:49.666 -05:00 [DBG] Adding auth_time claim with value: 1520479727
2018-03-07 22:28:49.731 -05:00 [INF] AuthenticationScheme: Identity.Application signed in.
2018-03-07 22:28:49.735 -05:00 [INF] User created a new account with password.
2018-03-07 22:28:50.202 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-07 22:28:50.206 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 09:24:57.238 -05:00 [DBG] Using Identity.Application as default scheme for authentication
2018-03-09 09:24:57.293 -05:00 [DBG] Using Identity.External as default scheme for sign-in
2018-03-09 09:24:57.296 -05:00 [DBG] Using Identity.External as default scheme for sign-out
2018-03-09 09:24:57.298 -05:00 [DBG] Using Identity.Application as default scheme for challenge
2018-03-09 09:24:57.300 -05:00 [DBG] Using Identity.Application as default scheme for forbid
2018-03-09 09:24:57.746 -05:00 [DBG] Starting token cleanup
2018-03-09 09:25:09.390 -05:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-03-09 09:25:16.550 -05:00 [DBG] Augmenting SignInContext
2018-03-09 09:25:18.164 -05:00 [DBG] Adding idp claim with value: local
2018-03-09 09:25:18.167 -05:00 [DBG] Adding amr claim with value: pwd
2018-03-09 09:25:18.170 -05:00 [DBG] Adding auth_time claim with value: 1520605516
2018-03-09 09:25:18.189 -05:00 [INF] AuthenticationScheme: Identity.Application signed in.
2018-03-09 09:25:18.560 -05:00 [INF] {
  "Name": "User Login Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1000,
  "Username": "dimortizp91@gmail.com",
  "SubjectId": "f6ac8e90-d578-428e-9d5e-557a53901551",
  "DisplayName": "dimortizp91@gmail.com",
  "Endpoint": "UI",
  "ActivityId": "0HLC5P64J6A3M:00000002",
  "TimeStamp": "2018-03-09T14:25:18Z",
  "ProcessId": 15080,
  "LocalIpAddress": "127.0.0.1:33426",
  "RemoteIpAddress": "::1"
}
2018-03-09 09:25:18.597 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 09:25:18.601 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 09:25:18.813 -05:00 [DBG] 1 persisted grants found for f6ac8e90-d578-428e-9d5e-557a53901551
2018-03-09 09:25:22.540 -05:00 [DBG] mvc found in database: true
2018-03-09 09:25:22.871 -05:00 [DBG] Found ["openid","profile"] identity scopes in database
2018-03-09 09:25:23.761 -05:00 [DBG] Found ["api1"] API scopes in database
2018-03-09 09:45:19.735 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 09:45:19.741 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 09:46:38.090 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 09:46:38.093 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 09:49:10.383 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 09:49:10.387 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 09:49:10.432 -05:00 [INF] AuthenticationScheme: Identity.Application signed out.
2018-03-09 09:49:10.436 -05:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-03-09 09:49:10.439 -05:00 [INF] AuthenticationScheme: Identity.TwoFactorUserId signed out.
2018-03-09 09:49:10.465 -05:00 [INF] {
  "Name": "User Logout Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1002,
  "SubjectId": "f6ac8e90-d578-428e-9d5e-557a53901551",
  "DisplayName": "dimortizp91@gmail.com",
  "ActivityId": "0HLC5P64J6A3P:00000001",
  "TimeStamp": "2018-03-09T14:49:10Z",
  "ProcessId": 15080,
  "LocalIpAddress": "127.0.0.1:33426",
  "RemoteIpAddress": "::1"
}
2018-03-09 10:08:08.754 -05:00 [DBG] Using Identity.Application as default scheme for authentication
2018-03-09 10:08:08.809 -05:00 [DBG] Using Identity.External as default scheme for sign-in
2018-03-09 10:08:08.811 -05:00 [DBG] Using Identity.External as default scheme for sign-out
2018-03-09 10:08:08.814 -05:00 [DBG] Using Identity.Application as default scheme for challenge
2018-03-09 10:08:08.816 -05:00 [DBG] Using Identity.Application as default scheme for forbid
2018-03-09 10:08:09.147 -05:00 [DBG] Starting token cleanup
2018-03-09 10:46:50.908 -05:00 [DBG] Augmenting SignInContext
2018-03-09 10:46:52.196 -05:00 [DBG] Adding idp claim with value: local
2018-03-09 10:46:52.200 -05:00 [DBG] Adding amr claim with value: pwd
2018-03-09 10:46:52.204 -05:00 [DBG] Adding auth_time claim with value: 1520610410
2018-03-09 10:46:52.231 -05:00 [INF] AuthenticationScheme: Identity.Application signed in.
2018-03-09 10:46:52.468 -05:00 [INF] {
  "Name": "User Login Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1000,
  "Username": "dimortizp91@gmail.com",
  "SubjectId": "f6ac8e90-d578-428e-9d5e-557a53901551",
  "DisplayName": "dimortizp91@gmail.com",
  "Endpoint": "UI",
  "ActivityId": "0HLC5PU8S3DCH:00000002",
  "TimeStamp": "2018-03-09T15:46:52Z",
  "ProcessId": 6676,
  "LocalIpAddress": "127.0.0.1:24763",
  "RemoteIpAddress": "::1"
}
2018-03-09 10:46:52.512 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:46:52.516 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:48:51.815 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:48:51.821 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:50:26.219 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:50:26.222 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:50:30.594 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:50:30.598 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:50:37.685 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:50:37.689 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:50:37.726 -05:00 [INF] AuthenticationScheme: Identity.Application signed out.
2018-03-09 10:50:37.730 -05:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-03-09 10:50:37.733 -05:00 [INF] AuthenticationScheme: Identity.TwoFactorUserId signed out.
2018-03-09 10:50:37.755 -05:00 [INF] {
  "Name": "User Logout Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1002,
  "SubjectId": "f6ac8e90-d578-428e-9d5e-557a53901551",
  "DisplayName": "dimortizp91@gmail.com",
  "ActivityId": "0HLC5PU8S3DCR:00000003",
  "TimeStamp": "2018-03-09T15:50:37Z",
  "ProcessId": 6676,
  "LocalIpAddress": "127.0.0.1:24763",
  "RemoteIpAddress": "::1"
}
2018-03-09 10:51:23.985 -05:00 [DBG] Augmenting SignInContext
2018-03-09 10:51:23.988 -05:00 [DBG] Adding idp claim with value: local
2018-03-09 10:51:23.991 -05:00 [DBG] Adding amr claim with value: pwd
2018-03-09 10:51:23.994 -05:00 [DBG] Adding auth_time claim with value: 1520610683
2018-03-09 10:51:23.998 -05:00 [INF] AuthenticationScheme: Identity.Application signed in.
2018-03-09 10:51:24.122 -05:00 [INF] {
  "Name": "User Login Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1000,
  "Username": "dimortizp91@gmail.com",
  "SubjectId": "f6ac8e90-d578-428e-9d5e-557a53901551",
  "DisplayName": "dimortizp91@gmail.com",
  "Endpoint": "UI",
  "ActivityId": "0HLC5PU8S3DCR:00000005",
  "TimeStamp": "2018-03-09T15:51:24Z",
  "ProcessId": 6676,
  "LocalIpAddress": "127.0.0.1:24763",
  "RemoteIpAddress": "::1"
}
2018-03-09 10:51:24.158 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:51:24.162 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:51:31.559 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:51:31.563 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:51:33.252 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:51:33.256 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:51:33.262 -05:00 [INF] AuthenticationScheme: Identity.Application signed out.
2018-03-09 10:51:33.265 -05:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-03-09 10:51:33.268 -05:00 [INF] AuthenticationScheme: Identity.TwoFactorUserId signed out.
2018-03-09 10:51:33.273 -05:00 [INF] {
  "Name": "User Logout Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1002,
  "SubjectId": "f6ac8e90-d578-428e-9d5e-557a53901551",
  "DisplayName": "dimortizp91@gmail.com",
  "ActivityId": "0HLC5PU8S3DCS:00000005",
  "TimeStamp": "2018-03-09T15:51:33Z",
  "ProcessId": 6676,
  "LocalIpAddress": "127.0.0.1:24763",
  "RemoteIpAddress": "::1"
}
2018-03-09 10:54:13.334 -05:00 [DBG] Augmenting SignInContext
2018-03-09 10:54:13.338 -05:00 [DBG] Adding idp claim with value: local
2018-03-09 10:54:13.341 -05:00 [DBG] Adding amr claim with value: pwd
2018-03-09 10:54:13.344 -05:00 [DBG] Adding auth_time claim with value: 1520610853
2018-03-09 10:54:13.347 -05:00 [INF] AuthenticationScheme: Identity.Application signed in.
2018-03-09 10:54:13.471 -05:00 [INF] {
  "Name": "User Login Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1000,
  "Username": "dimortizp91@gmail.com",
  "SubjectId": "f6ac8e90-d578-428e-9d5e-557a53901551",
  "DisplayName": "dimortizp91@gmail.com",
  "Endpoint": "UI",
  "ActivityId": "0HLC5PU8S3DCV:00000007",
  "TimeStamp": "2018-03-09T15:54:13Z",
  "ProcessId": 6676,
  "LocalIpAddress": "127.0.0.1:24763",
  "RemoteIpAddress": "::1"
}
2018-03-09 10:54:13.500 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:54:13.505 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:55:53.680 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:55:53.684 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:55:59.877 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:55:59.880 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:56:02.483 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:56:02.486 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-09 10:56:02.494 -05:00 [INF] AuthenticationScheme: Identity.Application signed out.
2018-03-09 10:56:02.499 -05:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-03-09 10:56:02.508 -05:00 [INF] AuthenticationScheme: Identity.TwoFactorUserId signed out.
2018-03-09 10:56:02.512 -05:00 [INF] {
  "Name": "User Logout Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1002,
  "SubjectId": "f6ac8e90-d578-428e-9d5e-557a53901551",
  "DisplayName": "dimortizp91@gmail.com",
  "ActivityId": "0HLC5PU8S3DD3:00000003",
  "TimeStamp": "2018-03-09T15:56:02Z",
  "ProcessId": 6676,
  "LocalIpAddress": "127.0.0.1:24763",
  "RemoteIpAddress": "::1"
}
2018-03-09 11:08:09.806 -05:00 [INF] Clearing 0 tokens
2018-03-09 12:08:10.432 -05:00 [INF] Clearing 0 tokens
2018-03-09 13:08:11.028 -05:00 [INF] Clearing 0 tokens
2018-03-12 09:29:40.691 -05:00 [DBG] Using Identity.Application as default scheme for authentication
2018-03-12 09:29:40.836 -05:00 [DBG] Using Identity.External as default scheme for sign-in
2018-03-12 09:29:40.839 -05:00 [DBG] Using Identity.External as default scheme for sign-out
2018-03-12 09:29:40.840 -05:00 [DBG] Using Identity.Application as default scheme for challenge
2018-03-12 09:29:40.842 -05:00 [DBG] Using Identity.Application as default scheme for forbid
2018-03-12 09:29:42.422 -05:00 [DBG] Starting token cleanup
2018-03-12 09:41:44.608 -05:00 [DBG] Using Identity.Application as default scheme for authentication
2018-03-12 09:41:44.722 -05:00 [DBG] Using Identity.External as default scheme for sign-in
2018-03-12 09:41:44.728 -05:00 [DBG] Using Identity.External as default scheme for sign-out
2018-03-12 09:41:44.740 -05:00 [DBG] Using Identity.Application as default scheme for challenge
2018-03-12 09:41:44.759 -05:00 [DBG] Using Identity.Application as default scheme for forbid
2018-03-12 09:41:45.994 -05:00 [DBG] Starting token cleanup
2018-03-12 09:43:30.791 -05:00 [DBG] Augmenting SignInContext
2018-03-12 09:43:32.011 -05:00 [DBG] Adding idp claim with value: local
2018-03-12 09:43:32.014 -05:00 [DBG] Adding amr claim with value: pwd
2018-03-12 09:43:32.018 -05:00 [DBG] Adding auth_time claim with value: 1520865810
2018-03-12 09:43:32.041 -05:00 [INF] AuthenticationScheme: Identity.Application signed in.
2018-03-12 09:43:32.456 -05:00 [INF] {
  "Name": "User Login Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1000,
  "Username": "dimortizp91@gmail.com",
  "SubjectId": "f6ac8e90-d578-428e-9d5e-557a53901551",
  "DisplayName": "dimortizp91@gmail.com",
  "Endpoint": "UI",
  "ActivityId": "0HLC84TGLG4HU:00000003",
  "TimeStamp": "2018-03-12T14:43:32Z",
  "ProcessId": 4308,
  "LocalIpAddress": "127.0.0.1:14946",
  "RemoteIpAddress": "::1"
}
2018-03-12 09:43:32.533 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-12 09:43:32.541 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-12 09:43:56.123 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-12 09:43:56.133 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-12 09:44:14.364 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-12 09:44:14.367 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-12 09:45:00.592 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-12 09:45:00.595 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-12 09:45:03.751 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-12 09:45:03.756 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-12 09:45:03.797 -05:00 [INF] AuthenticationScheme: Identity.Application signed out.
2018-03-12 09:45:03.801 -05:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-03-12 09:45:03.805 -05:00 [INF] AuthenticationScheme: Identity.TwoFactorUserId signed out.
2018-03-12 09:45:03.827 -05:00 [INF] {
  "Name": "User Logout Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1002,
  "SubjectId": "f6ac8e90-d578-428e-9d5e-557a53901551",
  "DisplayName": "dimortizp91@gmail.com",
  "ActivityId": "0HLC84TGLG4HS:00000007",
  "TimeStamp": "2018-03-12T14:45:03Z",
  "ProcessId": 4308,
  "LocalIpAddress": "127.0.0.1:14946",
  "RemoteIpAddress": "::1"
}
2018-03-12 09:56:05.871 -05:00 [DBG] Augmenting SignInContext
2018-03-12 09:56:05.874 -05:00 [DBG] Adding idp claim with value: local
2018-03-12 09:56:05.877 -05:00 [DBG] Adding amr claim with value: pwd
2018-03-12 09:56:05.880 -05:00 [DBG] Adding auth_time claim with value: 1520866565
2018-03-12 09:56:05.884 -05:00 [INF] AuthenticationScheme: Identity.Application signed in.
2018-03-12 09:56:06.007 -05:00 [INF] {
  "Name": "User Login Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1000,
  "Username": "dimortizp91@gmail.com",
  "SubjectId": "f6ac8e90-d578-428e-9d5e-557a53901551",
  "DisplayName": "dimortizp91@gmail.com",
  "Endpoint": "UI",
  "ActivityId": "0HLC84TGLG4IE:00000001",
  "TimeStamp": "2018-03-12T14:56:06Z",
  "ProcessId": 4308,
  "LocalIpAddress": "127.0.0.1:14946",
  "RemoteIpAddress": "::1"
}
2018-03-12 09:56:06.061 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
2018-03-12 09:56:06.065 -05:00 [INF] AuthenticationScheme: Identity.Application was successfully authenticated.
